### Importar la biblioteca NumPy

In [26]:
import numpy as np

Array de una dimensión

In [27]:
array_example_1 = np.array([1, 2, 3, 4, 5])
print(array_example_1)

[1 2 3 4 5]


Array de dos dimensiones (Matriz)

In [28]:
array_2_dim = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(array_2_dim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Matriz random de tamaño elegido

In [29]:
matriz = np.random.random((2,4))
print(matriz)

[[0.46740341 0.19879192 0.21382054 0.65685326]
 [0.23434332 0.88695103 0.15798279 0.0906898 ]]


In [30]:
print(matriz.ndim)
print(matriz.shape)
print(matriz.size)
print(matriz.dtype)

2
(2, 4)
8
float64


In [38]:
print(array_2_dim[0])
print(array_2_dim[1])
print(array_2_dim[1,4])

[1 2 3 4 5]
[ 6  7  8  9 10]
10


Operaciones con vectores

In [39]:
x = np.array([2,4,6])
y = np.array([1,2,3])

x-y

array([1, 2, 3])

In [45]:
print(np.abs(x))
print(np.log(x))
print(np.sin(x))
print(np.max(x))
print(np.mean(x))

[2 4 6]
[0.69314718 1.38629436 1.79175947]
[ 0.90929743 -0.7568025  -0.2794155 ]
6
4.0
